[package]
name = "libmqm-sys"
version = "0.4.0"
description = "Native bindings to the IBM® MQ Interface (MQI) and MQ Administration Interface (MQAI)"
authors = [ "Warren Spits <warren@advantic.au>" ]
repository = "https://github.com/advantic-au/libmqm-sys"
license = "Apache-2.0"
readme = "README.md"
keywords = [ "message-queue", "messaging" ]
categories = [ "external-ffi-bindings", "asynchronous" ]

edition = "2021"
rust-version = "1.77"
links = "mqm"
build = "build/mod.rs"

[features]
default = ["link", "mqi_helpers", "bindgen"]
docsrs = ["link_api", "pcf", "exits", "mqai", "dlopen2"]

dlopen2 = ["dep:dlopen2"]
link = [ "link_mqm", "link_api" ]
link_mqm = []
link_api = []
mqi_helpers = []
pcf = []
exits = []
mqai = []
bindgen = ["dep:bindgen" ]

[dependencies]
dlopen2 = { version = "0.7.0", optional = true } 

[build-dependencies]
regex-lite = "0.1.6"
bindgen = { version = "0.70.1", optional = true }
cc = "1.1.18"

[package.metadata.docs.rs]
features = ["docsrs"]
no-default-features = true
