[workspace]

[[package]]
name = "libmqm-sys"
changelog_update = true
changelog_path = "CHANGELOG.md"
changelog_include = ["libmqm-default", "libmqm-constants"]

[[package]]
name = "libmqm-default"
changelog_update = false

[[package]]
name = "libmqm-constants"
changelog_update = false
