// Autogenerated code doesn't need checking
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(clippy::nursery)]

#[cfg(feature = "generate")]
mod gen {
    pub mod mapping {
        // This file is generated during the build process
        include!(concat!(env!("OUT_DIR"), "/mapping.rs"));
    }
    include!(concat!(env!("OUT_DIR"), "/new_types.rs"));
}

#[cfg(all(not(feature = "generate"), target_os = "windows", target_arch = "x86_64"))]
mod gen {

    mod mapping {
        include!("../pregen/x86_64-windows-mapping.rs");
    }
    include!("../pregen/x86_64-windows-new_types.rs");
}

pub use gen::mapping;
pub use gen::constants;
pub use gen::types;

pub(crate) mod agg_mapping {
    use crate::lookup::{BinarySearchSource, ConstSource, PhfSource};
    use super::mapping;

    type MqxaSource<'a> = ConstSource<BinarySearchSource<'a>, BinarySearchSource<'a>>;    
    /// Selectors for MQIA and MQCA combined
    pub const MQXA_FULL_CONST: MqxaSource = ConstSource(mapping::MQIA_CONST, mapping::MQCA_CONST);

    /// Combined MQRCCF and MQRC range
    pub const MQRC_FULL_CONST: ConstSource<PhfSource, PhfSource> = ConstSource(mapping::MQRC_CONST, mapping::MQRCCF_CONST);
}

