name: mqc-redist
description: Downloads the MQ client library redist from IBM

inputs:
  path:
    description: Path to download the MQ client library
    required: true

runs:
  using: composite
  steps:
    - name: Cache MQC redist
      uses: actions/cache@v4
      id: cache-mqc-redist
      with:
        path: ${{ inputs.path }}
        key: mqclient-${{ runner.os }}-${{ matrix.mq-client-version }}
    - if: ${{ steps.cache-mqc-redist.outputs.cache-hit != 'true' }}
      name: Download MQC client
      uses: eyfSV/setup-mqclient@v0.3.1
      with:
        mq-client-version: 9.4.0.5
        path: ${{ input.path }}
