[package]
name = "libmqm-default"
version = "0.10.0"
description = "IBM® MQ Interface (MQI), Programmable Command Format (PCF) and MQ Administration Interface (MQAI) structure defaults"
keywords = ["message-queue", "messaging"]
categories = ["external-ffi-bindings", "asynchronous"]
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build/main.rs"

[dependencies]
libmqm-sys = { version = "0.10.0", path = "../libmqm-sys", default-features = false }
document-features = { version = "0.2.10", optional = true }

[build-dependencies]
libmqm-sys = { version = "0.10.0", path = "../libmqm-sys", default-features = false }
prettyplease = { version = "0.2.31", optional = true }
syn = { version = "2.0.90", optional = true, default-features = false, features = [
    "full",
    "parsing",
] }

[lints]
workspace = true

[features]
default = ["mqc_9_2_0_0"]
pregen = ["generate", "pcf", "exits", "mqc_9_3_1_0", "libmqm-sys/mqc_latest"]
generate = [
    "libmqm-sys/struct_defaults",
    "dep:prettyplease",
    "dep:syn",
]

pcf = ["libmqm-sys/pcf"]     # Enable the PCF API
exits = ["libmqm-sys/exits"] # Enable the Exits API

docsrs = [
    "libmqm-sys/docsrs", # Ensure libmqm-sys uses built in docsrs mode
    "pcf",
    "exits",
    "mqc_9_3_1_0",       # Latest MQ version that affects included defaults
    "dep:document-features"
]

mqc_9_2_0_0 = ["libmqm-sys/mqc_9_2_0_0"]
mqc_9_3_0_0 = ["mqc_9_2_0_0", "libmqm-sys/mqc_9_3_0_0"]
mqc_9_3_1_0 = ["mqc_9_3_0_0", "libmqm-sys/mqc_9_3_1_0"]

[package.metadata.docs.rs]
features = ["docsrs"]
no-default-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
