[package]
name = "libmqm-constants"
version = "0.8.3"
description = "IBM® MQ Interface (MQI), Programmable Command Format (PCF) and MQ Administration Interface (MQAI) constant definitions"
categories = ["external-ffi-bindings", "asynchronous"]
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

build = "build/main.rs"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[features]
default = ["mqc_9_2_0_0"]

docsrs = [
    "libmqm-sys/docsrs",     # Ensure libmqm-sys uses built in docsrs mode
    "mqai",
    "exits",
    "pcf",
    "mqc_9_4_4_0",           # Latest MQ version
    "dep:document-features",
]

## Generate the constants (default is to use pregenerated constants)
generate = [
    "libmqm-sys/constant_lookup",
    "dep:prettyplease",
    "dep:syn",
    "dep:phf_codegen",
    "dep:regex-lite",
]

## Generate the constants and save them in the src folder
pregen = ["generate", "mqai", "exits", "pcf", "mqc_9_4_4_0"]

## Administrative Interface (MQAI) constants
mqai = ["pcf", "libmqm-sys/mqai"]

## MQ programmable exit related constants
exits = ["libmqm-sys/exits"]

## PCF related constants
pcf = ["libmqm-sys/pcf"]

## Minimum MQ client version 9.2.0.0
mqc_9_2_0_0 = ["libmqm-sys/mqc_9_2_0_0"]
## Minimum MQ client version 9.3.0.0
mqc_9_3_0_0 = ["libmqm-sys/mqc_9_3_0_0", "mqc_9_2_0_0"]
## Minimum MQ client version 9.3.1.0
mqc_9_3_1_0 = ["libmqm-sys/mqc_9_3_1_0", "mqc_9_3_0_0"]
## Minimum MQ client version 9.3.2.0
mqc_9_3_2_0 = ["libmqm-sys/mqc_9_3_2_0", "mqc_9_3_1_0"]
## Minimum MQ client version 9.3.3.0
mqc_9_3_3_0 = ["libmqm-sys/mqc_9_3_3_0", "mqc_9_3_2_0"]
## Minimum MQ client version 9.3.4.0
mqc_9_3_4_0 = ["libmqm-sys/mqc_9_3_4_0", "mqc_9_3_3_0"]
## Minimum MQ client version 9.3.5.0
mqc_9_3_5_0 = ["libmqm-sys/mqc_9_3_5_0", "mqc_9_3_4_0"]
## Minimum MQ client version 9.4.0.0
mqc_9_4_0_0 = ["libmqm-sys/mqc_9_4_0_0", "mqc_9_3_5_0"]
## Minimum MQ client version 9.4.1.0
mqc_9_4_1_0 = ["libmqm-sys/mqc_9_4_1_0", "mqc_9_4_0_0"]
## Minimum MQ client version 9.4.2.0
mqc_9_4_2_0 = ["libmqm-sys/mqc_9_4_2_0", "mqc_9_4_1_0"]
## Minimum MQ client version 9.4.3.0
mqc_9_4_3_0 = ["libmqm-sys/mqc_9_4_3_0", "mqc_9_4_2_0"]
## Minimum MQ client version 9.4.4.0
mqc_9_4_4_0 = ["libmqm-sys/mqc_9_4_4_0", "mqc_9_4_3_0"]

[dependencies]
libmqm-sys = { version = "0.10.1", default-features = false, path = "../libmqm-sys" }
phf = { default-features = false, version = "0.13.1" }
derive_more = { version = "2.0.1", features = [
    "from",
    "add",
    "add_assign",
    "display",
] }
document-features = { version = "0.2.10", optional = true }

[build-dependencies]
libmqm-sys = { version = "0.10.1", default-features = false, path = "../libmqm-sys" }
regex-lite = { version = "0.1.6", optional = true }
phf_codegen = { version = "0.13.1", optional = true }
phf_generator = { version = "0.12.1", optional = true }
prettyplease = { version = "0.2.31", optional = true }
syn = { version = "2.0.90", optional = true, default-features = false, features = [
    "full",
    "parsing",
] }

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["docsrs"]
no-default-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
