[package]
name = "libmqm-sys"
version = "0.8.0"
description = "IBM® MQ Interface (MQI), Programmable Command Format (PCF) and MQ Administration Interface (MQAI) bindings"
keywords = ["message-queue", "messaging"]
categories = ["external-ffi-bindings", "asynchronous"]
authors.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true

links = "mqm"
build = "build/main.rs"

[lints]
workspace = true

[features]
default = ["link", "mqc_9_2_0_0"]

## Generate the bindings and save them in the src folder
pregen = ["pcf", "exits", "mqai", "bindgen", "mqc_latest"]

## Enable runtime loading of the MQI library using [`dlopen2`](dlopen2)
dlopen2 = ["dep:dlopen2", "dep:libc"]

## [`Link`](link) the MQI library at compile time
link = ["link_mqm", "link_api"]
link_mqm = []
link_api = []

## Compile the string lookup functions from the MQI C headers
constant_lookup = ["versiongen", "dep:cc", "dep:bindgen"]

## Compile the struct initialisers from the MQI C headers
struct_defaults = ["bindgen", "dep:cc"]

## Enable structures for PCF
pcf = []

## Enable structures for exits
exits = []

## Enable structures and constants for MQAI
mqai = []

docsrs = ["link_api", "pcf", "exits", "mqai", "dlopen2", "mqc_latest", "dep:document-features"]

## Use [`bindgen`](https://docs.rs/bindgen/latest/bindgen/) to generate bindings
bindgen = ["versiongen", "dep:bindgen", "dep:regex-lite", "dep:syn", "dep:prettyplease"]

## Generate version file from MQC library
versiongen = [ "dep:regex-lite" ]

## Minimum MQ client version 9.2.0.0
mqc_9_2_0_0 = []
mqc_9_3_0_0 = ["mqc_9_2_0_0"] # Minimum MQ client version 9.3.0.0
mqc_9_3_1_0 = ["mqc_9_3_0_0"] # Minimum MQ client version 9.3.1.0
mqc_9_3_2_0 = ["mqc_9_3_1_0"] # Minimum MQ client version 9.3.2.0
mqc_9_3_3_0 = ["mqc_9_3_2_0"] # Minimum MQ client version 9.3.3.0
mqc_9_3_4_0 = ["mqc_9_3_3_0"] # Minimum MQ client version 9.3.4.0
mqc_9_3_5_0 = ["mqc_9_3_4_0"] # Minimum MQ client version 9.3.5.0
mqc_9_4_0_0 = ["mqc_9_3_5_0"] # Minimum MQ client version 9.4.0.0
mqc_9_4_1_0 = ["mqc_9_4_0_0"] # Minimum MQ client version 9.4.1.0
## Minimum MQ client version 9.4.2.0
mqc_9_4_2_0 = ["mqc_9_4_1_0"]

## Minimum MQ client version to the latest released
mqc_latest = ["mqc_9_4_2_0"]

[dependencies]
dlopen2 = { version = "0.8.0", optional = true }
libc = { version = "0.2.155", optional = true }
document-features = { version = "0.2.10", optional = true }

[build-dependencies]
regex-lite = { version = "0.1.6", optional = true }
bindgen = { version = "0.71.1", optional = true }
syn = { version = "2.0.101", optional = true, features = [ "parsing"] }
prettyplease = { version = "0.2", optional = true }
cc = { version = "1.1.18", optional = true }

[package.metadata.docs.rs]
features = ["docsrs"]
no-default-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
