// Autogenerated code doesn't need checking
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(clippy::nursery)]

use crate::lookup::{BinarySearchSource, ConstSource, PhfSource};

#[cfg(feature = "generate")]
mod generated {
    use crate::lookup::*;

    // This file is generated during the build process
    include!(concat!(env!("OUT_DIR"), "/mqconstants.rs"));
}

#[cfg(not(feature = "generate"))]
mod generated {
    use crate::lookup::*;
    // This file is pregenerated

    #[cfg(all(target_os = "windows", target_arch = "x86_64"))]
    include!("pregen/x86_64-windows-mqconstants.rs");

    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    include!("pregen/x86_64-linux-mqconstants.rs");

    #[cfg(target_os = "macos")]
    include!("pregen/any-macos-mqconstants.rs");
}

pub use generated::*;

type MqxaSource<'a> = ConstSource<BinarySearchSource<'a>, BinarySearchSource<'a>>;

/// Selectors for MQIA and MQCA combined
pub const MQXA_FULL_CONST: MqxaSource = ConstSource(MQIA_CONST, MQCA_CONST);

/// Combined MQRCCF and MQRC range
pub const MQRC_FULL_CONST: ConstSource<PhfSource, PhfSource> = ConstSource(MQRC_CONST, MQRCCF_CONST);
