name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  schedule: [cron: "40 4 * * 2"]

env:
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - client-version: 9.3
            feature: mqc_9_3_5_0
          - client-version: 9.4
            feature: mqc_9_4_5_0
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install MQ client
        uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: ${{ matrix.version.client-version }}
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "build"
      - uses: taiki-e/install-action@e43a5023a747770bfcb71ae048541a681714b951 # v2.62.33
        with:
          tool: nextest
      - name: Test
        run: cargo nextest run --profile ci --features ${{ matrix.version.feature }},pcf,exits,mqai,dlopen2
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}

  clippy_fmt:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable, beta ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install rust ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "build"
      - uses: taiki-e/install-action@e43a5023a747770bfcb71ae048541a681714b951 # v2.62.33
        with:
          tool: cargo-hack
      - name: Install MQ client
        uses: advantic-au/action-mq-client@stable
        id: mq-client
      - name: Lint with rustfmt
        run: |
          cargo fmt -- --check
      - name: Lint with clippy
        run: |
          cargo hack -p libmqm-sys --each-feature --include-features mqai,pcf,exits,dlopen2,link,mqc_latest,mock,bindgen --features bindgen clippy --tests
          cargo hack -p libmqm-sys --feature-powerset --depth 2 --include-features mqai,pcf,exits,dlopen2,link,mqc_latest,mock,default clippy --tests
          cargo hack -p libmqm-constants --feature-powerset --depth 2 --include-features mqai,pcf,exits,mqc_9_4_5_0,default,generate clippy --tests
          cargo hack -p libmqm-default --feature-powerset --depth 2 --include-features pcf,exits,mqc_9_3_1_0,default,generate clippy --tests
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}

  clippy_fmt_outcome:
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    name: Clippy and rustfmt outcome
    needs: [clippy_fmt]
    steps:
      - run: |
          if [[ ${NEEDS_CLIPPY_FMT} == "success" || ${NEEDS_CLIPPY_FMT} == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
        env:
          NEEDS_CLIPPY_FMT: ${{ needs.clippy_fmt.result }}

  minimum:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
      # Re-resolve Cargo.lock with minimal versions
      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: nightly # -Z option only available on nightly
      - run: cargo generate-lockfile -Z minimal-versions
      # Now verify that `cargo check` works with respect to the oldest possible
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: 1.82
      - name: Check code
        run: cargo check --locked --all-features
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - uses: taiki-e/install-action@e43a5023a747770bfcb71ae048541a681714b951 # v2.62.33
        with:
          tool: nextest
      - name: Test
        run: cargo nextest run --locked --profile ci --all-features
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}

  docs:
    name: docs-rs generation
    runs-on: ubuntu-24.04
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@e43a5023a747770bfcb71ae048541a681714b951 # v2.62.33
        with:
          tool: cargo-docs-rs
      - run: cargo docs-rs -p libmqm-sys --target x86_64-unknown-linux-gnu
      - run: cargo docs-rs -p libmqm-default --target x86_64-unknown-linux-gnu
      - run: cargo docs-rs -p libmqm-constants --target x86_64-unknown-linux-gnu
  pregen_arch:
    name: Generate bindings on emulated architectures
    needs: [pregen]
    strategy:
      fail-fast: false
      matrix:
        env:
          - arch: s390x
            distro: ubuntu24.04
            client_arch: S390X
          - arch: ppc64le
            distro: ubuntu24.04
            client_arch: PPC64LE
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Determine MQ version
        id: mq_version_pregen
        uses: ./.github/action/mq_version_pregen
        with:
          os: Linux
          arch: ${{ matrix.env.client_arch }}
      - name: Download MQ library
        uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: ${{ steps.mq_version_pregen.outputs.client-version }}
          os: Linux
          arch: ${{ matrix.env.client_arch }}
      - id: cache-target-restore
        name: Cache restore Rust target
        uses: actions/cache/restore@v5
        with:
          path: |
            **/target
          key: rust-target-pregen-${{ matrix.env.distro }}-${{ matrix.env.arch }}
      - name: Pregenerate arch container
        uses: uraimo/run-on-arch-action@d94c13912ea685de38fccc1109385b83fd79427d # v3.0.1
        with:
          arch: ${{ matrix.env.arch }}
          distro: ${{ matrix.env.distro }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${{ steps.mq-client.outputs.client-install-path }}:/opt/mqm"
            --volume "${PWD}:/working"
          install: |
            apt-get update -q -y --silent
            apt-get install -q -y --silent build-essential libclang-18-dev curl ca-certificates git
          env: |
            MQ_HOME: /opt/mqm
          run: |
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused --location --silent --show-error --fail https://sh.rustup.rs | sh -s -- --default-toolchain none -y
            . $HOME/.cargo/env
            rustup toolchain install stable --profile minimal
            export CARGO_INCREMENTAL=0
            export CARGO_TERM_COLOR=always
            cd /working
            cargo build --no-default-features --features pregen
      - id: cache-target-save
        name: Cache save Rust target
        if: ${{ steps.cache-target-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: |
            **/target
          key: rust-target-pregen-${{ matrix.env.distro }}-${{ matrix.env.arch }}

      - name: Detect pregenerated changes
        run: |
          git add -N libmqm-sys/src libmqm-default/src libmqm-constants/src
          git diff --stat --exit-code libmqm-sys/src libmqm-default/src libmqm-constants/src
  pregen:
    name: Generate bindings
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Determine MQ version
        id: mq_version_pregen
        uses: ./.github/action/mq_version_pregen
      - name: Install MQ client
        uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: ${{ steps.mq_version_pregen.outputs.client-version }}
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "build"
      - name: Refresh pregenerated content
        run: cargo build --no-default-features --features pregen
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Detect pregenerated changes
        run: |
          git add -N libmqm-sys/src libmqm-default/src libmqm-constants/src
          git diff --stat --exit-code libmqm-sys/src libmqm-default/src libmqm-constants/src
  pregen_outcome:
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    name: Pregen outcome
    needs: [pregen, pregen_arch]
    steps:
      - run: |
          if [[ (${NEEDS_PREGEN} == "success" || ${NEEDS_PREGEN} == "skipped") && \
                (${NEEDS_PREGEN_ARCH} == "success" || ${NEEDS_PREGEN_ARCH} == "skipped") ]]; then
            exit 0
          else
            exit 1
          fi
        env:
          NEEDS_PREGEN: ${{ needs.pregen.result }}
          NEEDS_PREGEN_ARCH: ${{ needs.pregen_arch.result }}
