name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  schedule: [cron: "40 4 * * 2"]

env:
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - client-version: 9.2.0.31
            feature: mqc_9_2_0_0
          - client-version: 9.3.0.27
            feature: mqc_9_3_0_0
          - client-version: 9.3.5.1
            feature: mqc_9_3_5_0
          - client-version: 9.4.2.0
            feature: mqc_9_4_2_0
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install MQ client
        uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: ${{ matrix.version.client-version }}
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          shared-key: "build"
      - name: Test
        run: cargo test --features ${{ matrix.version.feature }},pcf,exits,mqai,dlopen2
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
  
  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install stable
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: stable
          components: rustfmt
      - name: Lint with rustfmt
        run: cargo fmt -- --check
        
  clippy:
    strategy:
      fail-fast: false
      matrix:
        features:
          - ""
          - "--no-default-features"
          - "--all-features"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: latest
      - name: Install stable
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          shared-key: "build"
      - name: Lint with clippy 
        run: cargo clippy --tests --examples ${{ matrix.features }} --
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}

  minimum:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: latest
      # Re-resolve Cargo.lock with minimal versions
      - name: Install rust nightly
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: nightly # -Z option only available on nightly
      - run: cargo generate-lockfile -Z minimal-versions
      # Now verify that `cargo check` works with respect to the oldest possible
      - uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: 1.77
      - name: Check code
        run: cargo check --locked --all-features
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}

  docs:
    runs-on: ubuntu-24.04
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@ab3728c7ba6948b9b429627f4d55a68842b27f18 # v2.50.3
        with:
          tool: cargo-docs-rs
      - run: cargo docs-rs -p libmqm-sys --target x86_64-unknown-linux-gnu
      - run: cargo docs-rs -p libmqm-default --target x86_64-unknown-linux-gnu
  pregen:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install MQ client
        uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: latest
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
        with:
          shared-key: "build"
      - name: Refresh pregenerated content
        run: cargo build --no-default-features --features pregen
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Detect pregenerated changes
        run: |
          git add -N libmqm-sys/src libmqm-default/src libmqm-constants/src
          git diff --stat --exit-code libmqm-sys/src libmqm-default/src libmqm-constants/src
  pregen_outcome:
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    name: Pregen outcome
    needs: [pregen]
    steps:
      - run: |
          result="${NEEDS_RESULT}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi
        env:
          NEEDS_RESULT: ${{ needs.pregen.result }}
