name: libmqm-sys

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  MQ_HOME: /tmp/mqc_redist

jobs:
  mqc-redist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache MQC redist
        uses: actions/cache@v4
        id: cache-mqc-redist
        with:
          path: ${{ env.MQ_HOME }}
          key: mqc-redist-${{ hashFiles('scripts/download-redist.sh') }}
      - if: ${{ steps.cache-mqc-redist.outputs.cache-hit != 'true' }}
        name: Download MQC redist
        run: sh scripts/download-redist.sh ${{ env.MQ_HOME }}

  rustfmt-clippy:
    runs-on: ubuntu-latest
    needs: [mqc-redist]
    steps:
      - uses: actions/checkout@v4

      - name: MQC redist
        uses: actions/cache@v4
        id: cache-mqc-redist
        with:
          path: ${{ env.MQ_HOME }}
          key: mqc-redist-${{ hashFiles('scripts/download-redist.sh') }}

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --tests --all-features

  msrv:
    runs-on: ubuntu-latest
    needs: [mqc-redist]
    name: Current MSRV is 1.77
    steps:
      - uses: actions/checkout@v4

      - name: MQC redist
        uses: actions/cache@v4
        id: cache-mqc-redist
        with:
          path: ${{ env.MQ_HOME }}
          key: mqc-redist-${{ hashFiles('scripts/download-redist.sh') }}

      # Re-resolve Cargo.lock with minimal versions
      - uses: dtolnay/rust-toolchain@nightly # -Z option only available on nightly
      - run: cargo update -Z minimal-versions
      # Now check that `cargo build` works with respect to the oldest possible
      - uses: dtolnay/rust-toolchain@1.77
      - run: cargo build --all-features
