name: libmqm-sys

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  rustfmt-clippy:
    runs-on: ubuntu-latest

    env:
      MQ_HOME: /tmp/mqc_redist

    steps:
      - uses: actions/checkout@v4

      - name: Cache MQC redist
        uses: actions/cache@v3
        id: cache-mqc-redist
        with:
          path: ${{ env.MQ_HOME }}
          key: mqc-redist-${{ hashFiles('scripts/download-redist.sh') }}
      
      - if: ${{ steps.cache-mqc-redist.outputs.cache-hit != 'true' }}
        name: Download MQC redist
        run: sh scripts/download-redist.sh ${{ env.MQ_HOME }}

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --tests --all-features
