name: libmqm-sys

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  MQ_HOME: /tmp/mqc_redist
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mqc_redist
        with:
          path: ${{ env.MQ_HOME }}

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --tests --all-features

  minimum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/mqc_redist
        with:
          path: ${{ env.MQ_HOME }}
      # Re-resolve Cargo.lock with minimal versions
      - uses: dtolnay/rust-toolchain@nightly # -Z option only available on nightly
      - run: cargo generate-lockfile -Z minimal-versions
      # Now verify that `cargo check` works with respect to the oldest possible
      - uses: dtolnay/rust-toolchain@1.77
      - run: cargo check --locked --all-features

  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly # Required for cargo-docs-rs
      - uses: dtolnay/install@cargo-docs-rs
      - run: cargo docs-rs
