name: "Pregenerated content CI"

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths: ["**/build/**", "**/pregen/**"]
  schedule: [cron: "40 4 * * 2"]

permissions: {}

jobs:
  pregen:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install MQ client
        uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: latest
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"
      - name: Refresh pregenerated content
        run: cargo build --no-default-features --features pregen
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Detect pregenerated changes
        run: |
          git add -N libmqm-sys/src libmqm-default/src
          git diff --stat --exit-code libmqm-sys/src libmqm-default/src
