name: pregen-command
on:
  repository_dispatch:
    types: [pregen-command]

permissions: {}

jobs:
  pregen:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [windows-latest, ubuntu-24.04, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.SCD }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Switch to pregen branch
        shell: bash
        run: |
          PREGEN_BRANCH=pregen_${{ github.run_id }}
          git switch --track origin/${PREGEN_BRANCH} || git switch -c ${PREGEN_BRANCH}
      - name: Determine MQ version
        id: mq_version_pregen
        uses: ./.github/action/mq_version_pregen
      - uses: advantic-au/action-mq-client@stable
        id: mq_client
        with:
          client-version: ${{ steps.mq_version_pregen.outputs.client-version }}
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "build"
      - name: Run build and refresh generated source code
        run: cargo build --no-default-features --features pregen
        env:
          MQ_HOME: ${{ steps.mq_client.outputs.client-install-path }}
      - uses: qoomon/actions--setup-git@8e6bd30ac05e17a81b61169daae62cb6b7e61294 #v1.1
      - name: Modify pregen branch with refreshed pregen files
        shell: bash
        run: |
          git add libmqm-sys/src libmqm-default/src libmqm-constants/src
          git commit -m "chore: MQ client ${MQ_CLIENT_VERSION} ${{ runner.os }} ${{ runner.arch }}" && \
            git push --set-upstream origin pregen_${{ github.run_id }} || true
        env:
          MQ_CLIENT_VERSION: ${{ steps.mq_client.outputs.client-version }}
  pregen_arch:
    needs: [pregen]
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        env:
          - arch: s390x
            distro: ubuntu24.04
            client_arch: S390X
          - arch: ppc64le
            distro: ubuntu24.04
            client_arch: PPC64LE
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: write
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.SCD }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Switch to the pregen branch
        shell: bash
        run: |
          PREGEN_BRANCH=pregen_${{ github.run_id }}
          git switch --track origin/${PREGEN_BRANCH} || git switch -c ${PREGEN_BRANCH}
      - name: Determine MQ version
        id: mq_version_pregen
        uses: ./.github/action/mq_version_pregen
        with:
          os: Linux
          arch: ${{ matrix.env.client_arch }}
      - name: Download MQ library
        uses: advantic-au/action-mq-client@stable
        id: mq_client
        with:
          client-version: ${{ steps.mq_version_pregen.outputs.client-version }}
          os: Linux
          arch: ${{ matrix.env.client_arch }}
      - id: cache-target-restore
        name: Cache restore Rust target
        uses: actions/cache/restore@v5
        with:
          path: |
            **/target
          key: rust-target-pregen-${{ matrix.env.distro }}-${{ matrix.env.arch }}
      - name: Pregenerate arch container
        uses: uraimo/run-on-arch-action@d94c13912ea685de38fccc1109385b83fd79427d # v3.0.1
        with:
          arch: ${{ matrix.env.arch }}
          distro: ${{ matrix.env.distro }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${{ steps.mq_client.outputs.client-install-path }}:/opt/mqm"
            --volume "${PWD}:/working"
          install: |
            apt-get update -q -y --silent
            apt-get install -q -y --silent build-essential libclang-18-dev curl ca-certificates git
          env: |
            MQ_HOME: /opt/mqm
          run: |
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused --location --silent --show-error --fail https://sh.rustup.rs | sh -s -- --default-toolchain none -y
            . $HOME/.cargo/env
            rustup toolchain install stable --profile minimal
            export CARGO_INCREMENTAL=0
            export CARGO_TERM_COLOR=always
            cd /working
            cargo build --no-default-features --features pregen
      - id: cache-target-save
        name: Cache save Rust target
        if: ${{ steps.cache-target-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: |
            **/target
          key: rust-target-pregen-${{ matrix.env.distro }}-${{ matrix.env.arch }}
      - uses: qoomon/actions--setup-git@8e6bd30ac05e17a81b61169daae62cb6b7e61294 #v1.1
      - name: Modify pull request with refreshed pregen files
        shell: bash
        run: |
          git add libmqm-sys/src libmqm-default/src libmqm-constants/src
          git commit -m "chore: MQ client ${MQ_CLIENT_VERSION} Linux ${{ matrix.env.arch }}" && \
            git push --set-upstream origin pregen_${{ github.run_id }} || true
        env:
          MQ_CLIENT_VERSION: ${{ steps.mq_client.outputs.client-version }}
  pregen_merge:
    runs-on: ubuntu-24.04
    needs: [ pregen, pregen_arch ]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.SCD }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Merge pregen branch into pull request
        shell: bash
        run: |
          PREGEN_BRANCH=pregen_${{ github.run_id }}
          git merge --ff-only origin/${PREGEN_BRANCH} && git push && \
            git push origin :${PREGEN_BRANCH} || true