name: semver-command
on:
  repository_dispatch:
    types: [semver-command]

permissions: {}

jobs:
  semver:
    runs-on: ubuntu-24.04
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          token: ${{ secrets.SCD }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Install rust stable
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          shared-key: "build"
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@5b298c9520f7096a4683c0bd981a7ac5a7e249ae # v2.8