name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  slash_command_dispatch:
    runs-on: ubuntu-24.04
    permissions:
      issues: write # for reactions
      pull-requests: write # for reactions
    steps:
      - uses: peter-evans/slash-command-dispatch@9bdcd7914ec1b75590b790b844aa3b8eee7c683a # v4
        with:
          token: ${{ secrets.SCD }} 
          issue-type: pull-request
          commands: |
            pregen
            semver
