name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

permissions: {}

jobs:
  slash_command_dispatch:
    runs-on: ubuntu-24.04
    permissions:
      issues: write # for reactions
      pull-requests: write # for reactions
    steps:
      - uses: peter-evans/slash-command-dispatch@e1b4e266bc781656359bb7e462e228daf68c04f6 # v4
        with:
          token: ${{ secrets.SCD }} 
          issue-type: pull-request
          commands: |
            pregen
            semver
