use crate::lib;
use ::dlopen2::wrapper::WrapperApi;
#[derive(::dlopen2::wrapper::WrapperApi, Debug)]
pub struct MqWrapper {
    MQXEP: unsafe extern "C" fn(
        Hconfig: lib::MQHCONFIG,
        ExitReason: lib::MQLONG,
        Function: lib::MQLONG,
        pEntryPoint: lib::PMQFUNC,
        pExitOpts: lib::PMQXEPO,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQXCLWLN: unsafe extern "C" fn(
        pExitParms: lib::PMQWXP,
        CurrentRecord: lib::MQPTR,
        NextOffset: lib::MQLONG,
        pNextRecord: lib::PMQPTR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQXCNVC: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Options: lib::MQLONG,
        SourceCCSID: lib::MQLONG,
        SourceLength: lib::MQLONG,
        pSourceBuffer: lib::PMQCHAR,
        TargetCCSID: lib::MQLONG,
        TargetLength: lib::MQLONG,
        pTargetBuffer: lib::PMQCHAR,
        pDataLength: &mut lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQXDX: unsafe extern "C" fn(
        pDataConvExitParms: lib::PMQDXP,
        pMsgDesc: lib::PMQMD,
        InBufferLength: lib::MQLONG,
        pInBuffer: lib::PMQVOID,
        OutBufferLength: lib::MQLONG,
        pOutBuffer: lib::PMQVOID,
    ),
    MQZEP: unsafe extern "C" fn(
        Hconfig: lib::MQHCONFIG,
        Function: lib::MQLONG,
        pEntryPoint: lib::PMQFUNC,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddBag: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemValue: lib::MQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddByteString: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQBYTE,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddByteStringFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQBYTE,
        Operator: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddInquiry: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddInteger: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemValue: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddInteger64: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemValue: lib::MQINT64,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddIntegerFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemValue: lib::MQLONG,
        Operator: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddString: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqAddStringFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        Operator: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqBagToBuffer: unsafe extern "C" fn(
        OptionsBag: lib::MQHBAG,
        DataBag: lib::MQHBAG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        pDataLength: &mut lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqBufferToBag: unsafe extern "C" fn(
        OptionsBag: lib::MQHBAG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        DataBag: lib::MQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqClearBag: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqCountItems: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        pItemCount: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqCreateBag: unsafe extern "C" fn(
        Options: lib::MQLONG,
        pBag: lib::PMQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqDeleteBag: unsafe extern "C" fn(
        pBag: lib::PMQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqDeleteItem: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqExecute: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Command: lib::MQLONG,
        OptionsBag: lib::MQHBAG,
        AdminBag: lib::MQHBAG,
        ResponseBag: lib::MQHBAG,
        AdminQ: lib::MQHOBJ,
        ResponseQ: lib::MQHOBJ,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqGetBag: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hobj: lib::MQHOBJ,
        pMsgDesc: lib::PMQVOID,
        pGetMsgOpts: lib::PMQVOID,
        Bag: lib::MQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireBag: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        pItemValue: lib::PMQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireByteString: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQBYTE,
        pByteStringLength: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireByteStringFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQBYTE,
        pByteStringLength: lib::PMQLONG,
        pOperator: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireInteger: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        pItemValue: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireInteger64: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        pItemValue: lib::PMQINT64,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireIntegerFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        pItemValue: lib::PMQLONG,
        pOperator: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireItemInfo: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        pOutSelector: lib::PMQLONG,
        pItemType: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireString: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        pStringLength: lib::PMQLONG,
        pCodedCharSetId: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqInquireStringFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        pStringLength: lib::PMQLONG,
        pCodedCharSetId: lib::PMQLONG,
        pOperator: lib::PMQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqPad: unsafe extern "C" fn(
        pString: lib::PMQCHAR,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqPutBag: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hobj: lib::MQHOBJ,
        pMsgDesc: lib::PMQVOID,
        pPutMsgOpts: lib::PMQVOID,
        Bag: lib::MQHBAG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetByteString: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQBYTE,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetByteStringFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQBYTE,
        Operator: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetInteger: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        ItemValue: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetInteger64: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        ItemValue: lib::MQINT64,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetIntegerFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        ItemValue: lib::MQLONG,
        Operator: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetString: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqSetStringFilter: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        Selector: lib::MQLONG,
        ItemIndex: lib::MQLONG,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        Operator: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqTrim: unsafe extern "C" fn(
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQCHAR,
        pString: lib::PMQCHAR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    mqTruncateBag: unsafe extern "C" fn(
        Bag: lib::MQHBAG,
        ItemCount: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQBACK: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQBEGIN: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pBeginOptions: Option<&mut lib::MQBO>,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQBUFMH: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hmsg: lib::MQHMSG,
        pBufMsgHOpts: &lib::MQBMHO,
        pMsgDesc: lib::PMQVOID,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        pDataLength: &mut lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCB: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Operation: lib::MQLONG,
        pCallbackDesc: Option<&lib::MQCBD>,
        Hobj: lib::MQHOBJ,
        pMsgDesc: lib::PMQVOID,
        pGetMsgOpts: Option<&lib::MQGMO>,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCLOSE: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pHobj: &mut lib::MQHOBJ,
        Options: lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCMIT: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCONN: unsafe extern "C" fn(
        pQMgrName: &lib::MQCHAR48,
        pHconn: &mut lib::MQHCONN,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCONNX: unsafe extern "C" fn(
        pQMgrName: &lib::MQCHAR48,
        pConnectOpts: &mut lib::MQCNO,
        pHconn: &mut lib::MQHCONN,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCRTMH: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pCrtMsgHOpts: lib::PMQVOID,
        pHmsg: &mut lib::MQHMSG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQCTL: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Operation: lib::MQLONG,
        pControlOpts: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQDISC: unsafe extern "C" fn(
        pHconn: &mut lib::MQHCONN,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQDLTMH: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pHmsg: &mut lib::MQHMSG,
        pDltMsgHOpts: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQDLTMP: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hmsg: lib::MQHMSG,
        pDltPropOpts: lib::PMQVOID,
        pName: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQGET: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hobj: lib::MQHOBJ,
        pMsgDesc: lib::PMQVOID,
        pGetMsgOpts: lib::PMQVOID,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        pDataLength: &mut lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQINQ: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hobj: lib::MQHOBJ,
        SelectorCount: lib::MQLONG,
        pSelectors: lib::PMQLONG,
        IntAttrCount: lib::MQLONG,
        pIntAttrs: lib::PMQLONG,
        CharAttrLength: lib::MQLONG,
        pCharAttrs: lib::PMQCHAR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQINQMP: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hmsg: lib::MQHMSG,
        pInqPropOpts: lib::PMQVOID,
        pName: lib::PMQVOID,
        pPropDesc: lib::PMQVOID,
        pType: lib::PMQLONG,
        ValueLength: lib::MQLONG,
        pValue: lib::PMQVOID,
        pDataLength: &mut lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQMHBUF: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hmsg: lib::MQHMSG,
        pMsgHBufOpts: lib::PMQVOID,
        pName: lib::PMQVOID,
        pMsgDesc: lib::PMQVOID,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        pDataLength: &mut lib::MQLONG,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQOPEN: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pObjDesc: lib::PMQVOID,
        Options: lib::MQLONG,
        pHobj: &mut lib::MQHOBJ,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQPUT: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hobj: lib::MQHOBJ,
        pMsgDesc: lib::PMQVOID,
        pPutMsgOpts: lib::PMQVOID,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQPUT1: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pObjDesc: lib::PMQVOID,
        pMsgDesc: lib::PMQVOID,
        pPutMsgOpts: lib::PMQVOID,
        BufferLength: lib::MQLONG,
        pBuffer: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQSET: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hobj: lib::MQHOBJ,
        SelectorCount: lib::MQLONG,
        pSelectors: lib::PMQLONG,
        IntAttrCount: lib::MQLONG,
        pIntAttrs: lib::PMQLONG,
        CharAttrLength: lib::MQLONG,
        pCharAttrs: lib::PMQCHAR,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQSETMP: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hmsg: lib::MQHMSG,
        pSetPropOpts: lib::PMQVOID,
        pName: lib::PMQVOID,
        pPropDesc: lib::PMQVOID,
        Type: lib::MQLONG,
        ValueLength: lib::MQLONG,
        pValue: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQSTAT: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Type: lib::MQLONG,
        pStatus: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQSUB: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        pSubDesc: lib::PMQVOID,
        pHobj: Option<&mut lib::MQHOBJ>,
        pHsub: lib::PMQHOBJ,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
    MQSUBRQ: unsafe extern "C" fn(
        Hconn: lib::MQHCONN,
        Hsub: lib::MQHOBJ,
        Action: lib::MQLONG,
        pSubRqOpts: lib::PMQVOID,
        pCompCode: &mut lib::MQLONG,
        pReason: &mut lib::MQLONG,
    ),
}
